FROM node:8

RUN mkdir -p /usr/node-auth/src

WORKDIR /usr/node-auth/

COPY package.json /usr/node-auth/

RUN npm install

COPY ./src /usr/node-auth/src

EXPOSE 5000
CMD [ "npm", "start" ]

#docker build -t kostas/node_image dockerImage
#docker build -t kostas/node_image .
#docker run -p 5000:5000 -d kostas/node_image
#docker inspect --format "{{ .NetworkSettings.Networks.bridge.IPAddress }}" <container>  
#docker run -it -p 172.17.0.2:5000:5000 -d kostas/node_image